package com.github.educationissimple.audio.entities

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Represents an audio category entity for storing in the Room Database.
 * This entity is used to manage categories of audio items.
 * @param id The unique identifier of the audio category. It is auto-generated by the Room database.
 * @param name The name of the audio category (e.g., "Audiobooks", "Podcasts"). Stored in a case-insensitive manner.
 */
@Entity(
    tableName = "audio_categories",
    indices = [
        Index("name", unique = true)
    ]
)
data class AudioCategoryDataEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    @ColumnInfo(collate = ColumnInfo.NOCASE) val name: String
)